# auto-generated by MCP Hub
try:
    from fastmcp import FastMCP
except ImportError:
    from mcp.server.fastmcp import FastMCP

import httpx
import os
import json
import logging
import time
from datetime import datetime, UTC
from typing import Optional, Dict, Any, List

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("Swagger")

mcp = FastMCP("Swagger")
BASE_URL = "https://petstore.swagger.io/v2"
SERVER_ID = "69c51d76fa7ceed068c18b06"
HUB_API_URL = os.environ.get("HUB_API_URL", "https://backend-phi-ebon-40.vercel.app")


# ── Insight POST ─────────────────────────────────────────────────────────────
# Called synchronously (awaited) INSIDE the same async task that handles the
# MCP message — this guarantees it runs before Vercel sends the response back.
async def _post_insight(tool_name: str, status: str, duration_ms: float,
                        error: Optional[str] = None,
                        input_size: int = 0, output_size: int = 0):
    payload = {
        "server_id": SERVER_ID,
        "tool_name": tool_name,
        "request_type": "tool",
        "execution_time_ms": duration_ms,
        "status": status,
        "error": error,
        "input_size": input_size,
        "output_size": output_size,
        "timestamp": datetime.now(UTC).isoformat(),
    }
    _url = HUB_API_URL.rstrip('/') + '/api/insights/track'
    try:
        async with httpx.AsyncClient(timeout=5.0) as _c:
            _r = await _c.post(_url, json=payload)
            logger.info(f"[insight] {tool_name} {status} {duration_ms:.0f}ms -> HTTP {_r.status_code}")
    except Exception as _e:
        logger.warning(f"[insight] POST failed: {_e}")


import os
AUTH_HEADERS = { "api_key": os.environ.get('API_KEY', "") }


async def make_request(
    method: str, path: str,
    query_params: Optional[Dict] = None, body: Any = None,
    content_type: str = "application/json", extra_headers: Optional[Dict] = None,
):
    url = BASE_URL + path
    headers = AUTH_HEADERS.copy()
    if extra_headers:
        headers.update(extra_headers)
    logger.info(f"{method} {url}")
    async with httpx.AsyncClient(timeout=30.0) as client:
        if query_params:
            query_params = {k: v for k, v in query_params.items() if v is not None}
        kwargs: Dict[str, Any] = {"headers": headers, "params": query_params}
        if body is not None and method.upper() not in ["GET", "DELETE"]:
            kwargs["data" if content_type == "multipart/form-data" else "json"] = body
        try:
            resp = await client.request(method, url, **kwargs)
            resp.raise_for_status()
            try:
                return resp.json()
            except Exception:
                return resp.text
        except httpx.HTTPStatusError as e:
            return {"error": f"API returned {e.response.status_code}", "details": e.response.text}
        except Exception as e:
            return {"error": str(e)}


async def _root_handler(request):
    from starlette.responses import JSONResponse
    try:
        tools_list = [t.name for t in getattr(mcp, '_tools', {}).values()]
    except Exception:
        tools_list = []
    return JSONResponse({'status': 'ready', 'server': getattr(mcp, 'name', 'mcp-server'),
                         'tools': tools_list, 'hub': HUB_API_URL})

@mcp.tool(name="uploadFile")
async def uploadFile(petId: int, additionalMetadata: Optional[str] = None, file: Optional[str] = None):
    'uploads an image'
    return await make_request(
        "POST",
        f"/pet/{petId}/uploadImage",
        query_params=None,
        body={ "additionalMetadata": additionalMetadata, "file": file },
        content_type="multipart/form-data",
        extra_headers={},
    )

@mcp.tool(name="addPet")
async def addPet(id: Optional[int] = None, category: Optional[Dict[str, Any]] = None, name: Optional[str] = None, photoUrls: Optional[List[Any]] = None, tags: Optional[List[Any]] = None, status: Optional[str] = None):
    'Add a new pet to the store'
    return await make_request(
        "POST",
        f"/pet",
        query_params=None,
        body={ "id": id, "category": category, "name": name, "photoUrls": photoUrls, "tags": tags, "status": status },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updatePet")
async def updatePet(id: Optional[int] = None, category: Optional[Dict[str, Any]] = None, name: Optional[str] = None, photoUrls: Optional[List[Any]] = None, tags: Optional[List[Any]] = None, status: Optional[str] = None):
    'Update an existing pet'
    return await make_request(
        "PUT",
        f"/pet",
        query_params=None,
        body={ "id": id, "category": category, "name": name, "photoUrls": photoUrls, "tags": tags, "status": status },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="findPetsByStatus")
async def findPetsByStatus(status: str):
    'Multiple status values can be provided with comma separated strings'
    return await make_request(
        "GET",
        f"/pet/findByStatus",
        query_params={ "status": status },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="findPetsByTags")
async def findPetsByTags(tags: str):
    'Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.'
    return await make_request(
        "GET",
        f"/pet/findByTags",
        query_params={ "tags": tags },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getPetById")
async def getPetById(petId: int):
    'Returns a single pet'
    return await make_request(
        "GET",
        f"/pet/{petId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updatePetWithForm")
async def updatePetWithForm(petId: int, name: Optional[str] = None, status: Optional[str] = None):
    'Updates a pet in the store with form data'
    return await make_request(
        "POST",
        f"/pet/{petId}",
        query_params=None,
        body={ "name": name, "status": status },
        content_type="multipart/form-data",
        extra_headers={},
    )

@mcp.tool(name="deletePet")
async def deletePet(petId: int):
    'Deletes a pet'
    return await make_request(
        "DELETE",
        f"/pet/{petId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getInventory")
async def getInventory():
    'Returns a map of status codes to quantities'
    return await make_request(
        "GET",
        f"/store/inventory",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="placeOrder")
async def placeOrder(id: Optional[int] = None, petId: Optional[int] = None, quantity: Optional[int] = None, shipDate: Optional[str] = None, status: Optional[str] = None, complete: Optional[bool] = None):
    'Place an order for a pet'
    return await make_request(
        "POST",
        f"/store/order",
        query_params=None,
        body={ "id": id, "petId": petId, "quantity": quantity, "shipDate": shipDate, "status": status, "complete": complete },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getOrderById")
async def getOrderById(orderId: int):
    'For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions'
    return await make_request(
        "GET",
        f"/store/order/{orderId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="deleteOrder")
async def deleteOrder(orderId: int):
    'For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors'
    return await make_request(
        "DELETE",
        f"/store/order/{orderId}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUsersWithListInput")
async def createUsersWithListInput():
    'Creates list of users with given input array'
    return await make_request(
        "POST",
        f"/user/createWithList",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="getUserByName")
async def getUserByName(username: str):
    'Get user by user name'
    return await make_request(
        "GET",
        f"/user/{username}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="updateUser")
async def updateUser(username: str, id: Optional[int] = None, username_body: Optional[str] = None, firstName: Optional[str] = None, lastName: Optional[str] = None, email: Optional[str] = None, password: Optional[str] = None, phone: Optional[str] = None, userStatus: Optional[int] = None):
    'This can only be done by the logged in user.'
    return await make_request(
        "PUT",
        f"/user/{username}",
        query_params=None,
        body={ "id": id, "username": username_body, "firstName": firstName, "lastName": lastName, "email": email, "password": password, "phone": phone, "userStatus": userStatus },
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="deleteUser")
async def deleteUser(username: str):
    'This can only be done by the logged in user.'
    return await make_request(
        "DELETE",
        f"/user/{username}",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="loginUser")
async def loginUser(username: str, password: str):
    'Logs user into the system'
    return await make_request(
        "GET",
        f"/user/login",
        query_params={ "username": username, "password": password },
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="logoutUser")
async def logoutUser():
    'Logs out current logged in user session'
    return await make_request(
        "GET",
        f"/user/logout",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUsersWithArrayInput")
async def createUsersWithArrayInput():
    'Creates list of users with given input array'
    return await make_request(
        "POST",
        f"/user/createWithArray",
        query_params=None,
        body=None,
        content_type="application/json",
        extra_headers={},
    )

@mcp.tool(name="createUser")
async def createUser(id: Optional[int] = None, username: Optional[str] = None, firstName: Optional[str] = None, lastName: Optional[str] = None, email: Optional[str] = None, password: Optional[str] = None, phone: Optional[str] = None, userStatus: Optional[int] = None):
    'This can only be done by the logged in user.'
    return await make_request(
        "POST",
        f"/user",
        query_params=None,
        body={ "id": id, "username": username, "firstName": firstName, "lastName": lastName, "email": email, "password": password, "phone": phone, "userStatus": userStatus },
        content_type="application/json",
        extra_headers={},
    )

from starlette.applications import Starlette
from starlette.responses import JSONResponse, Response
from starlette.routing import Route
from starlette.requests import Request as StarletteRequest

if __name__ == "__main__":
    mcp.run()
else:
    try:
        from mcp.server.sse import SseServerTransport
        _transport = SseServerTransport("/messages/")

        async def _sse_endpoint(request):
            _inner = getattr(mcp, '_mcp_server', None) or getattr(mcp, 'server', None) or mcp
            async with _transport.connect_sse(request.scope, request.receive, request._send) as (r, w):
                await _inner.run(r, w, _inner.create_initialization_options(), raise_exceptions=False)
            return Response()

        async def _sse_post_endpoint(request: StarletteRequest):
            raw = await request.body()
            try:
                body = json.loads(raw)
                method = body.get('method')
                if method == 'initialize':
                    return JSONResponse({'server': getattr(mcp, 'name', 'mcp-server'), 'capabilities': {'tools': True, 'resources': False, 'prompts': False}})
                elif method == 'tools/list':
                    tools_list = []
                    try:
                        for t in getattr(mcp, '_tools', {}).values():
                            tools_list.append({'name': t.name, 'description': getattr(t, 'description', '')})
                    except:
                        pass
                    return JSONResponse({'tools': tools_list})
                elif method == 'tools/call':
                    params = body.get('params', {})
                    name = params.get('name')
                    args = params.get('arguments', {})
                    _start = time.perf_counter()
                    _status = 'success'
                    _error = None
                    try:
                        sanitized = ''.join(c if c.isalnum() else '_' for c in name)
                        if sanitized and sanitized[0].isdigit(): sanitized = 't_' + sanitized
                        tool_fn = globals().get(sanitized)
                        if tool_fn:
                            res = await tool_fn(**args)
                            return JSONResponse({'content': [{'type': 'text', 'text': str(res)}]})
                        else:
                            raise ValueError(f'Tool {name} not found')
                    except Exception as e:
                        _status = 'error'
                        _error = str(e)
                        return JSONResponse({'isError': True, 'content': [{'type': 'text', 'text': str(e)}]})
                    finally:
                        _dur = (time.perf_counter() - _start) * 1000
                        await _post_insight(name, _status, _dur, _error, len(raw), 0)
                return JSONResponse({'error': 'Unsupported method'}, status_code=400)
            except Exception as e:
                return JSONResponse({'error': str(e)}, status_code=500)

        async def _messages_endpoint(request: StarletteRequest):
            raw = await request.body()
            _start = time.perf_counter()
            _tool_name = None
            _is_tool_call = False
            try:
                _msg = json.loads(raw)
                if _msg.get('method') == 'tools/call':
                    _is_tool_call = True
                    _tool_name = (_msg.get('params') or {}).get('name', 'unknown')
            except Exception:
                pass
            async def _replay(): return {'type': 'http.request', 'body': raw, 'more_body': False}
            _status = 'success'
            _error = None
            try:
                await _transport.handle_post_message(request.scope, _replay, request._send)
            except Exception as _exc:
                _status = 'error'
                _error = str(_exc)
            finally:
                if _is_tool_call and _tool_name:
                    _dur = (time.perf_counter() - _start) * 1000
                    await _post_insight(_tool_name, _status, _dur, _error, len(raw), 0)
            return Response(status_code=202)

        app = Starlette(routes=[
            Route("/", _root_handler),
            Route("/sse", _sse_endpoint, methods=["GET"]),
            Route("/sse", _sse_post_endpoint, methods=["POST"]),
            Route("/messages/", _messages_endpoint, methods=["POST"]),
            Route("/messages", _messages_endpoint, methods=["POST"]),
            Route("/{path:path}", _root_handler),
        ])
    except Exception as _e:
        logger.error(f"Startup failed: {_e}")
        async def _err(r): return JSONResponse({'status': 'error', 'detail': str(_e)}, status_code=500)
        app = Starlette(routes=[Route('/', _err), Route('/{path:path}', _err)])
